---
title: "Impressum"
---

Medienagentur Geschichte Dr. Tillmann Bendikowski Rönkkoppel 23a 22159 Hamburg

Telefon: 040 / 57 14 69 61 Telefax: 040 / 57 14 85 21 info\@medienagentur-geschichte.de

Verantwortlich im Sinne des MdStV: Dr. Tillmann Bendikowski

Steuer-Nummer: 54/581/11938 Finanzamt Hamburg-Eimsbüttel

Website: www.diegeisel.de

Inhalt des Onlineangebotes: Die Medienagentur Geschichte übernimmt keinerlei Gewähr für die Aktualität, Korrektheit, Vollständigkeit oder Qualität der bereitgestellten Informationen. Haftungsansprüche gegen die Medienagentur Geschichte, welche sich auf Schäden materieller oder ideeller Art beziehen, die durch die Nutzung oder Nichtnutzung der dargebotenen Informationen bzw. durch die Nutzung fehlerhafter und unvollständiger Informationen verursacht wurden, sind grundsätzlich ausgeschlossen, sofern seitens der Medienagentur Geschichte kein nachweislich vorsätzliches oder grob fahrlässiges Verschulden vorliegt. Alle Angebote sind freibleibend und unverbindlich. Die Medienagentur Geschichte behält es sich ausdrücklich vor, Teile der Seiten oder das gesamte Angebot ohne gesonderte Ankündigung zu verändern, zu ergänzen, zu löschen oder die Veröffentlichung zeitweise oder endgültig einzustellen.

Verweise auf andere Internetseiten (Links): Das Landesgericht Hamburg hat mit Urteil vom 12.05.1998 sowie das Landgericht Potsdam mit Urteil vom 08.07.1999 (3 O 317/99) entschieden, dass man durch die Ausbringung eines Links die Inhalte der gelinkten Seite ggf. mit zu verantworten hat. Dies kann -- so die Landgerichte -- nur dadurch verhindert werden, dass man sich ausdrücklich von diesen Inhalten distanziert. Wir haben auf unseren Internetseiten Links zu anderen Seiten in Internet gelegt. Für all diese Links möchten wir ausdrücklich betonen, dass wir keinerlei Einfluss auf die Gestaltung und die Inhalte der gelinkten Seiten haben. Deshalb distanziert sich die Medienagentur Geschichte hiermit ausdrücklich von allen Inhalten der gelinkten Seiten auf unserer Homepage. Diese Erklärung gilt für alle auf unserer Internetseite ausgebrachten Links und für alle Inhalte der Seiten, zu denen die Banner führen.

Urheber- und Kennzeichenrecht: Die Medienagentur Geschichte ist bestrebt, in allen Publikationen die Urheberrechte der verwendeten Grafiken, Tondokumente, Videosequenzen und Texte zu beachten, von ihr selbst erstellte Grafiken, Tondokumente, Videosequenzen und Texte zu nutzen oder auf lizenzfreie Grafiken, Tondokumente, Videosequenzen und Texte zurückzugreifen. Alle innerhalb des Internetangebotes genannten und ggf. durch Dritte geschützten Marken- und Warenzeichen unterliegen uneingeschränkt den Bestimmungen des jeweils gültigen Kennzeichenrechts und den Besitzrechten der jeweiligen eingetragenen Eigentümer. Allein aufgrund der bloßen Nennung ist nicht der Schluss zu ziehen, dass Markenzeichen nicht durch Rechte Dritter geschützt sind! Das Copyright für veröffentlichte, von der Medienagentur Geschichte selbst erstellte Objekte bleibt allein beim Autor der Seiten. Eine Vervielfältigung oder Verwendung solcher Grafiken, Tondokumente, Videosequenzen und Texte in anderen elektronischen oder gedruckten Publikationen ist ohne ausdrückliche Zustimmung des Autors nicht gestattet.

Rechtswirksamkeit dieses Haftungsausschlusses: Dieser Haftungsausschluss ist als Teil des Internetangebotes zu betrachten, von dem aus auf diese Seite verwiesen wurde. Sofern Teile oder einzelne Formulierungen dieses Textes der geltenden Rechtslage nicht, nicht mehr oder nicht vollständig entsprechen sollten, bleiben die übrigen Teile des Dokumentes in ihrem Inhalt und ihrer Gültigkeit davon unberührt.
